### ISSUE TITLE
subscribe with variable filters in addition to topicName

### ISSUE THREAD

**Issue by nick-cwt** [camunda/camunda-external-task-client-java#15]
The Camunda REST API for fetchAndLock (https://docs.camunda.org/manual/7.9/reference/rest/external-task/fetch/) hints that process variable values can be used to filter the tasks on the server, in addition to the topicName. This would allow us to support multiple flavors of external task worker, working independently to achieve a common result.
For example, our service task is called "eat ice-cream" and there is a process variable called flavor. At the moment, I have to subscribe to the external task "eat-ice-cream", but then check the flavor variable = "coconut" before I say the task is done. If the flavor is "vanilla", do I throw a BPMN exception, or should I just unlock the external task without completing it? If I throw the exception, the implication is that I know for sure that no other worker is going to eat vanilla ice-cream. If I don't, Camunda will keep sending me a task to eat vanilla ice-cream, and I can't.

**Comment by nick-cwt** [comment]
Thanks for the quick response, Tassilo.

I agree that it's a feature request. I don't know how to create one of those, I'm afraid.

I see my worker going into a tight loop, keep re-fetching and unlocking the task to eat vanilla ice-cream. If I force a back off, somehow, that's going to introduce latency into my coconut ice-cream eating. I suppose if nobody is prepared to eat the flavor of ice-cream, the BPMN can have a boundary timer, but how long should it wait? Especially if the other worker is feeding some downstream kids with vanilla ice-cream, and they aren't available right now.
Right now, I will throw a BPMN exception (to keep the BPMN simple), but I would like to not have the BPMN care which flavors are edible. I would have some external ice-cream monitor send email to our CEO, if the consumption of vanilla ice-cream was outside some SLA.

Thanks,
Nick.

**Comment by tasso94** [comment]
Hey Nick,

don't worry. With the ticket [CAM-9350](https://app.camunda.com/jira/browse/CAM-9350) I already created the feature request for you ;).

What about introducing an external task topic for each flavour? This would allow to subscribe the client directly to the flavour.

Cheers,
Tassilo
