### ISSUE TITLE
Client able to use the processVariables filter?

### ISSUE THREAD

**Issue by StephenOTT** [camunda/camunda-external-task-client-java#19]
edit:

Changing this around to make sure of the api:

Does the Client have the ability to use the processVariables filter as part of the API?

**Comment by tasso94** [comment]
Hi Stephen,

currently it is not possible to apply a filter to only 'Fetch and Lock' for External Tasks by a specific variable name (i. e., a variable exists in the scope of the respective External Task).

There exists a ticket for this [Feature Request](https://app.camunda.com/jira/browse/CAM-9350).

Does this answer your question?

Cheers,
Tassilo
