### ISSUE TITLE
API for asynchronous completion of tasks

### ISSUE THREAD

**Issue by falko** [camunda/camunda-external-task-client-java#25]
In my current customer workshop, we tried to build a worker that sends messages to Kafka when an external task is fetched and locked. It also has a Kafka consumer that waits for an asynchronous response message. When that message is received, the external task should be completed. However, the current ExternalTaskClient API does not provide any method to simply complete a task by id.

**Comment by tasso94** [comment]
Hi Falko,

thank you for reaching out to us with your feature request. Right now there is no plan to add such a feature. However, we would appreciate it if you would contribute to the code base.

Cheers,
Tassilo

**Comment by falko** [comment]
@berndruecker FYI

**Comment by berndruecker** [comment]
Is there a possibility to vote on issues on GitHub somehow? Would love to vote it up 👍

**Comment by nevries** [comment]
Had exactly the same demand.
My worker spins off a Camunda process and I want to complete when that process (long-running, that is, couple of minutes) finishes.
For now I use the following work-around: 
((ExternalTaskClientImpl) externalTaskClient).getTopicSubscriptionManager().getEngineClient().complete()

Maybe you can make something like that possible without touching internal API.

**Comment by berndruecker** [comment]
@nevries: Some customer context? Maybe we can leverage this to channel it into the stake meeting?

**Comment by Firestorm87** [comment]
Same question here.
Most unique Feature of Zeebe is the possibility to have an async external Worker for bpmn Services.
Would be great to have similar possibilities in camundas external Tasks.

Need for example for Tasks Delegate via Messages or if external Worker themselves need User Input for task completion.

**Comment by nevries** [comment]
Added ticket https://jira.camunda.com/browse/CAM-11909

**Comment by impactpractise** [comment]
On the roadmap and prioritized 👍
