### ISSUE TITLE
Builder for asyncResponseTimeout doesnt allow to disable

### ISSUE THREAD

**Issue by wesleyjconnor** [camunda/camunda-external-task-client-java#26]
The ExternalTaskClientBuilder throws exception if the asyncResponseTimeout is null or <=0 however when using the fluent builder and system properties its not possible to disable using the builder, for example 

'options' is a prebuilt object containing system properties with -1 as a default (for not configured)

Ideally we could do

    ExternalTaskClient client = ExternalTaskClient.create()
    .baseUrl(options.getUrl())
    .workerId(options.getWorkerId())
    .lockDuration(options.getLockDuration())
    .asyncResponseTimeout(options.getLongPollingTimeout()); //will not work since it will throw exception on -1
    .maxTasks(options.getMaxTasks());
    .build();

The workaround is
 
    ExternalTaskClientBuilder externalTaskClientBuilder = ExternalTaskClient.create()
    .baseUrl(options.getUrl())
    .workerId(options.getWorkerId())
    .lockDuration(options.getLockDuration())
    .maxTasks(options.getMaxTasks());

    if (options.getLongPollingTimeout() > 0) {
      externalTaskClientBuilder.asyncResponseTimeout(options.getLongPollingTimeout());
    }
    ExternalTaskClient client = externalTaskClientBuilder.build();

Which is not very fluent

I suggest to allow -1 as a 'disabled' value and null still as a exceptional case

**Comment by tasso94** [comment]
Closed on behalf of #27
