### ISSUE TITLE
Client swallows errors represented in json

### ISSUE THREAD

**Issue by Krever** [camunda/camunda-external-task-client-java#5]
Because current implementation relies on `org.apache.http.impl.client.AbstractResponseHandler` it executes the following code: 
```
    @Override
    public T handleResponse(final HttpResponse response)
            throws HttpResponseException, IOException {
        final StatusLine statusLine = response.getStatusLine();
        final HttpEntity entity = response.getEntity();
        if (statusLine.getStatusCode() >= 300) {
            EntityUtils.consume(entity);
            throw new HttpResponseException(statusLine.getStatusCode(),
                    statusLine.getReasonPhrase());
        }
        return entity == null ? null : handleEntity(entity);
    }
```

When executing `complete` on a task, all the errors are reprsented in body as a json, so this removes access to the real error and leaves the user with not very meaningful
> org.camunda.bpm.client.exception.NotResumedException: TASK/CLIENT-01009 Exception while completing the external task: The corresponding process instance could not be resumed

This is quite a critical for us.

**Comment by tasso94** [comment]
Hi,

to see what went wrong exactly you could check the log file of the application server you are running Camunda Workflow Engine.

Would this be a suitable option for you?

Cheers,
Tassilo

**Comment by Krever** [comment]
Thanks for response!

> Would this be a suitable option for you?

Not really. I could, of course, check the engine logs, but it requires a number of additional hops when looking at the logs. Also, we are running in a highly distributed environment with custom log format containing custom trace-ids and this wont apply to camunda logs.  

As a workaround, we could, of course, mark the task as complete with custom http request, but let's keep that as a last resort.

**Comment by tasso94** [comment]
Hey,

at the moment we are busy with the release of Camunda BPM.
We will come back to you as soon as possible but not before the end of this week/beginning of next week.

Cheers,
Tassilo

**Comment by koevskinikola** [comment]
Hi @Krever,

Can you share the BPMN model where this problem occurrs, or even better, a basic model (or an example configuration) where it occurrs, so that we can reproduce it on our side?

Best,
Nikola

**Comment by Krever** [comment]
@koevskinikola 
Sure, thanks for attention!

The model definition I paste at the end of the post but it is a very simple one: it has a single external task with a single output variable defined as a groovy script. This script is invalid on purpose. In fact it could be any kind of model error after the external task definiton.

Client code:
```
val client = ExternalTaskClient.create()
        .baseUrl(camundaBaseUrl)
        .build()

client.subscribe("external-task")
        .handler((externalTask: ExternalTask, externalTaskService: ExternalTaskService) => {
          try {
            externalTaskService.complete(externalTask)
          } catch {
            case e: Throwable => println(e)
          }
        })
        .open()
```
its scala but this shouldnt be a problem. We subscribe to the topic and complete it immediately. In case of error we print it to stdout.

When we start a process, following line shows up in my stdout:

> org.camunda.bpm.client.exception.NotResumedException: TASK/CLIENT-01009 Exception while completing the external task: The corresponding process instance could not be resumed

But if I run it in debug and catch the response body (or call API with curl), the real error is:

> {"type":"ScriptEvaluationException","message":"Unable to evaluate script while executing activity 'Task_0b8ffxn' in the process definition with id 'Process_1:1:3b9fad87-67d7-11e8-a67c-0242ac110004': groovy.lang.MissingPropertyException: No such property: invalidScript for class: Script2"}

which is much more detailed.

**Comment by koevskinikola** [comment]
Hey @Krever,

Thanks! I managed to reproduce the issue, so I created a [JIRA ticket](https://app.camunda.com/jira/browse/CAM-9124) for it.

However, at the moment we have several tickets with higher priority, so this issue might not be resolved immediately. But, you can always speed up the process with a contribution from your side. We'll review the code, give guidelines, and, if acceptable merge it with the codebase asap.

Cheers,
Nikola
