### ISSUE TITLE
TopicSubsciption#close() is not synchronous

### ISSUE THREAD

**Issue by Krever** [camunda/camunda-external-task-client-java#6]
I just tried to write docker-based e2e automated tests with scala/sbt and spotted this. I have a setup similar to the following (its pseudo-code to express the idea)
```
test1 {
  val handler1 = client.subscribe("topic1")....
  val subscription = handler1.open()
  triggerProcess()
  verifyLogic()
  subscription.close()
}
test2 {
  val handler2 = client.subscribe("topic1")....
  val subscription = handler2.open()
  triggerProcess()
  verifyLogic()
  subscription.close()
}
```
And when I start the process instance in second test my `handler1` gets invoked. A workaround is to to invoke `client.stop()` which seems to solve the problem.

I would like to know if its known behavior. If so, if it's classified as an issue or not. I could spend some time to produce a minimal example of this behavior. If it's expected I think it should be mentioned in the javadoc of the `close` method. 

I tried to investigate, but `close` leads only to subscription being removed from the list of subscriptions, which is completely synchronous...

**Comment by sdorokhova** [comment]
Hi Klever,

yes, current implementation has this drawback, which is related with the fact, that we tried to avoid too much synchronization. Currently, if some list of external tasks is being processed at the moment by the client (they are fetched and locked and the handlers are being executed), and at this moment you close (or open) the subscription, it won't have affect immediately. It will have affect only for the next bunch of fetched and locked tasks. I know, that it looks not super beautiful and we should definitely document this.

Can you may be elaborate your use case?

Cheers,
Svetlana

**Comment by Krever** [comment]
Okey, that sounds reasonable and the docs comment should be enough to save future users some time investigating the issue.

I don't know what exactly you would like to know but here it goes: we are implementing a process relying completely on external tasks, so we can run standard, unmodified docker image of camunda. Then we would like to have an end-to-end test for such a process where we:

1. start the image
1. deploy the process definition
1. Run test scenarios:
    1. setup handlers for required topics
    1. start the process
    1. wait for completion
    1. verify what was triggered

We have done all of that,  but when we run multiple scenarios handlers from the first one steal the messages from the next one. As I said, we managed to workaround this by stopping the client completely after each test. I will be happy to answer any other questions if they come :)

**Comment by sdorokhova** [comment]
Hi @Krever ,

thank you for additional information. You explain testing situation, but of course I'm more curious of runtime production scenarios, where such behavior could be a problem.

Anyway, I've adjusted the Javadocs in 7ac2457e71577033ade8f3a56146dfa44ef2ebb5

**Comment by Krever** [comment]
Thanks! It's not an issue in production use :)
